baseurl = "https://example.org/"
languageCode = "en-us"
title = "Making #MeToo Count"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "icon/favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Making #MeToo Count"

		[params.navigation.links]
			about     = "About"
			event     = "Event"
			services  = "Speakers"
			resources = "Resources"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Making #MeToo Count"
		subtitle   = " "
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "About"
		description = "In 2018, over a dozen women came forward and spoke to The Chronicle of Higher Education about their experiences of sexual harassment by Jorge I. Domínguez — then a professor in Harvard’s Government department."
		# description2 = "The Domínguez case sparked a national conversation about sexual harassment in academia. Students, staff, alumni, and faculty in the Harvard Government Department [called on the University](https://www.thecrimson.com/article/2019/2/28/dominguez-external-review/) to commission an external review into the institutional failures revealed by the Domínguez case."
		# description3 = "Just two months after the Chronicle article came out, Harvard’s graduate students voted to unionize. In the wake of the reporting on the Domínguez case, student workers across campus came together to [demand stronger protections against harassment and discrimination](http://harvardgradunion.org/members/nocarveout/)."
		buttonText  = "Read the Story"
		buttonLink = "https://www.chronicle.com/interactives/harvard-harassment"

  # Event section
	[params.event]
	heading = "Event"
	#	headline = "Monday February 3, 2020"
	#	time = "4:30 -- 6pm"
	#	subline = "CGIS South S010"
		# description = "A panel discussion on turning Harvard's #MeToo problem into lasting institutional change."
		[params.event.button]
		text = "Facebook event page"
		link = "facebook.com/events/482521759103893/"
		[params.event.button2]
		text = "Directions"
		link = "https://www.google.com/maps/place/Cgis+South,+1730+Cambridge+St,+Cambridge,+MA+02138,+USA/@42.3750154,-71.1153363,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37744397bb925:0xcf4f795206016674!8m2!3d42.3750154!4d-71.1131476?hl=en"
		


	# Service section
	[params.services]
		headline1 = "Panel 1: Speaking Out"
		des1 = "We are honored to be joined by four of the women who spoke out about the Dominguez case, to talk about why they are still in this fight."
		headline2 = "Panel 2: Strategies for Creating Change"
		des2 = "How can we turn the #MeToo movement into lasting institutional change?"
		
		 [[params.services.list]]
         icon = "img/photos/tk.jpg"
         title = "Terry Karl"

              
     [[params.services.list]]
          icon = "img/photos/charna.jpg"
          title = "Charna Sherman"

		 [[params.services.list]]
          icon = "img/photos/nienke.jpg"
          title = "Nienke Grossman"

      [[params.services.list]]
          icon = "img/photos/suzanna.jpeg"
          title = "Suzanna Challen"


     [[params.services.list2]]
			    icon = "img/photos/p15.jpg"
			    title = "Debra Katz"
			    description = "America's top #MeToo lawyer, recently representing Dr. Christine Blasey-Ford. Founding partner o Katz, Marshall & Banks."

		 [[params.services.list2]]
         icon = "img/photos/sejal.jpg"
         title = "Sejal Singh"
         description = "Harvard Law student, co-founder of the People's Parity Project, organizer for the Harvard Graduate Student Union (HGSU-UAW)"
    
     # Portfolio modals
	[params.portfolio.modal]
        client = "Test"
        date = "1"
        category = "Cat"
        buttonText = "ooo"
        
   # Contact section
	[params.resources]
	#	headline = "Resources"

	# Contact section
	[params.contact]
		headline = "Get In Touch"
		description = "If you would like to contact the event organizers, please send us an email at:"
		# phone = "123-456-6789"
		email = "makingmetoocount@gmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
